---
- name: Create Admin User
  user: name=admin password={{vault_admin_password}} groups=sudo append=yes shell=/bin/bash

- name: Add Admin Authorized Key
  authorized_key: user=admin
                  key="{{ vault_common_public_key }}"
                  state=present

- name: Create Deploy User
  user: name=deploy password={{vault_deploy_password}} groups=www-data append=yes shell=/bin/bash

- name: Add Deploy Authorized Key
  authorized_key: user=deploy
                  key="{{ vault_common_public_key }}"
                  state=present
