language: python
python: '2.7'
env:
  - ROLE=$(echo $TRAVIS_REPO_SLUG | cut -f2 -d'/')
sudo: required
virtualenv:
  system_site_packages: true
before_install: true
install: true
script: ./tests/specs.sh --install $(echo $TRAVIS_REPO_SLUG | cut -f2 -d'/')
notifications:
  slack:
    secure: f4s+CrjKmv58411G0QNkR5cro7MkzlIxAuujYovn/wA59LSvKNF/aK+wwrBya1IQZfH80CmcHZGKOKBVM7dDpnsEMkH5U/9Fu3NO1M8YqPcSQWSXvkEdvbkUgWoXbkUOWqxsbbe5SiBnbYDj40Z6zR5oWe/j79QmNb5Hj9UWDws=
