ruby_makeopts: "-j2"

ruby_deps:
  - autoconf
  - automake
  - bison
  - build-essential
  - curl
  - exuberant-ctags
  - git-core
  - libc6-dev
  - libncurses5-dev
  - libffi-dev
  - libreadline6
  - libreadline6-dev
  - libreadline-dev
  - libsqlite3-0
  - libsqlite3-dev
  - libssl-dev
  - libtool
  - libyaml-dev
  - libxml2-dev
  - libxslt1-dev
  - openssl
  - sqlite3
  - zlib1g
  - zlib1g-dev
